package minio

import (
	"context"
	"io"
	"net/http"
	"net/url"
	"time"
	_ "unsafe"

	"github.com/minio/minio-go/v7"
)

//go:linkname makeTargetURL github.com/minio/minio-go/v7.(*Client).makeTargetURL
func makeTargetURL(client *minio.Client, bucketName, objectName, bucketLocation string, isVirtualHostStyle bool, queryValues url.Values) (*url.URL, error)

// requestMetadata - is container for all the values to make a request.
type requestMetadata struct {
	// If set newRequest presigns the URL.
	presignURL bool

	// User supplied.
	bucketName         string
	objectName         string
	queryValues        url.Values
	customHeader       http.Header
	extraPresignHeader http.Header
	expires            int64

	// Generated by our internal code.
	bucketLocation   string
	contentBody      io.Reader
	contentLength    int64
	contentMD5Base64 string // carries base64 encoded md5sum
	contentSHA256Hex string // carries hex encoded sha256sum
	streamSha256     bool
	addCrc           bool
	trailer          http.Header // (http.Request).Trailer. Requires v4 signature.
}

//go:linkname executeMethod github.com/minio/minio-go/v7.(*Client).executeMethod
func executeMethod(client *minio.Client, ctx context.Context, method string, metadata requestMetadata) (*http.Response, error)

//go:linkname httpRespToErrorResponse github.com/minio/minio-go/v7.httpRespToErrorResponse
func httpRespToErrorResponse(resp *http.Response, bucketName, objectName string) error

//go:linkname copyDestOptionsValidate github.com/minio/minio-go/v7.CopyDestOptions.validate
func copyDestOptionsValidate(opts minio.CopyDestOptions) error

//go:linkname copySrcOptionsValidate github.com/minio/minio-go/v7.CopySrcOptions.validate
func copySrcOptionsValidate(opts minio.CopySrcOptions) error

//go:linkname amzExpirationToExpiryDateRuleID github.com/minio/minio-go/v7.amzExpirationToExpiryDateRuleID
func amzExpirationToExpiryDateRuleID(expiration string) (time.Time, string)
